'use strict';

var braintree_translation = {
  payingWith: 'Plătește cu {{paymentSource}}',
  chooseAnotherWayToPay: 'Alege altă metodă de plată',
  chooseAWayToPay: 'Alege o metodă de plată',
  otherWaysToPay: 'Alte metode de plată',
  cardVerification: 'Verificarea Cardului',
  // Errors
  fieldEmptyForCvv: 'Te rugăm să completezi cu un CVV.',
  fieldEmptyForExpirationDate: 'Te rugăm să completezi cu data expirării.',
  fieldEmptyForCardholderName: 'Te rugăm să completezi cu numele deținătorului.',
  fieldEmptyForNumber: 'Te rugăm să completezi cu un număr de card.',
  fieldEmptyForPostalCode: 'Te rugăm să completezi cu un cod poștal.',
  fieldInvalidForCvv: 'Acest cod de securitate nu este valid.',
  fieldInvalidForExpirationDate: 'Această dată a expirării nu este validă.',
  fieldInvalidForNumber: 'Acest număr de card nu este valid.',
  fieldInvalidForPostalCode: 'Acest cod poștal nu este valid.',
  fieldTooLongForCardholderName: 'Numele deținătorului trebuie să aibe cel mult 256 caractere.',
  genericError: 'A intervenit o eroare de partea noastră.',
  hostedFieldsTokenizationFailOnDuplicateError: 'Acest card este deja înregistrat ca metodă de plată.',
  hostedFieldsFailedTokenizationError: 'Te rugăm să verifici informațiile și să încerci din nou.',
  hostedFieldsTokenizationCvvVerificationFailedError: 'Verificarea cardului de credit a eșuat. Te rugăm să verifici informațiile și să încerci din nou.',
  hostedFieldsTokenizationNetworkErrorError: 'Eroare de rețea. Te rugăm să încerci din nou.',
  hostedFieldsFieldsInvalidError: 'Te rugăm să verifici informațiile și să încerci din nou.',
  paypalAccountTokenizationFailedError: 'A intervenit ceva în timpul adăugării contului de PayPal. Te rugăm să încerci din nou.',
  paypalFlowFailedError: 'A intervenit ceva în timpul conectării cu PayPal. Te rugăm să încerci din nou.',
  paypalTokenizationRequestActiveError: 'Autorizarea plății cu PayPal este deja în progres.',
  applePayTokenizationError: 'A intervenit o eroare de rețea în timpul procesării plății cu Apple Pay. Te rugăm să încerci din nou.',
  applePayActiveCardError: 'Adaugă un card acceptat în portofelul Apple Pay.',
  venmoCanceledError: 'S-a întâmplat ceva. Asigură-te că ai instalată cea mai recentă versiune a aplicației Venmo și că browser-ul tău acceptă trecerea către Venmo.',
  venmoAppFailedError: 'Aplicația Venmo nu a putut fi găsită.',
  unsupportedCardTypeError: 'Acest tip de card nu este suportat. Te rugăm să încerci un alt card.',
  // Card form
  cardholderNameLabel: 'Numele deținătorului',
  cardNumberLabel: 'Numărul cardului',
  cvvLabel: 'CVV',
  cvvThreeDigitLabelSubheading: '(3 cifre)',
  cvvFourDigitLabelSubheading: '(4 cifre)',
  expirationDateLabel: 'Data expirării',
  expirationDateLabelSubheading: '(LL/AA)',
  cardholderNamePlaceholder: 'Numele deținătorului',
  expirationDatePlaceholder: 'LL/AA',
  postalCodeLabel: 'Cod poștal',
  payWithCard: 'Plătește cu card',
  // Payment Method descriptions
  endingIn: 'Se termină în ••{{lastTwoCardDigits}}',
  Card: 'Card',
  PayPal: 'PayPal',
  'PayPal Credit': 'PayPal Credit',
  'Apple Pay': 'Apple Pay',
  'Google Pay': 'Google Pay',
  'Venmo': 'Venmo',
  'American Express': 'American Express',
  Discover: 'Discover',
  'Diners Club': 'Diners Club',
  MasterCard: 'Mastercard',
  Visa: 'Visa',
  JCB: 'JCB',
  Maestro: 'Maestro',
  UnionPay: 'UnionPay'
};